[package]
name = "moneta"
version = "0.3.2"
edition = "2021"
authors = ["Michael Amrhein <michael@adrhinum.de>"]
description = "Currency-safe computations with money amounts."
readme = "README.md"
homepage = "https://github.com/mamrhein/money.rs"
repository = "https://github.com/mamrhein/money.rs"
documentation = "https://docs.rs/moneta/"
license-file = "LICENSE.TXT"
keywords = ["money", "currency", "exchange"]
categories = ["data-structures", "mathematics"]

[dependencies]
fpdec = "0.5.2"
fpdec-core = "0.5"
quantities = { version = "0.9.0", features = ["fpdec"] }

[features]
default = ["std"]
std = []
